name: Print Pull Request Context

on: 
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: echo "GITHUB_CONTEXT='${{ toJSON(github.event) }}'"
        